# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

deploy:
    # only:
    #    - master
    image: maven:3.9.6-eclipse-temurin-21 # docker image with Maven
    before_script:
        - ./ci/setup-mvn-proxy.sh
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - chmod 400 $CI_SSH_KEY
    script:
        - cd users
        - mvn clean package
        - which scp
        - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY target/users.war gitlabci@192.168.75.36:/opt/tomcat/webapps/users.war
        - cd ..
        - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY -r api/ gitlabci@192.168.75.36:~/
        - ssh -o StrictHostKeyChecking=no -i $CI_SSH_KEY gitlabci@192.168.75.36 'cd api && npm i && pm2 delete all && pm2 start index.js'
